#pragma once
// Default values:
#define L_THRESHOLD_DEFAULT 70
#define B_THRESHOLD_DEFAULT 20
#define A_THRESHOLD_DEFAULT 20

//SHI TOMASI

#define ST_QUALITY_LEVEL_DEFAULT 0.01
#define MAX_CORNERS_DEFAULT 500
#define ST_MIN_DISTANCE_DEFAULT 10
#define ST_BLOCK_SIZE 3
#define ST_GRADIENT_SIZE 3
#define ST_K 0.04
//LUCAS KANADE
#define LK_WIN_SIZE 15
#define LK_MIN_EIG_VALUE 0.03
#define LK_MAX_LEVEL 10